# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Anim

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ByteDataTrack(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ByteDataTrack()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsByteDataTrack(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ByteDataTrack
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ByteDataTrack
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ByteDataTrackStart(builder):
    builder.StartObject(1)

def Start(builder):
    ByteDataTrackStart(builder)

def ByteDataTrackAddValue(builder, value):
    builder.PrependUint8Slot(0, value, 0)

def AddValue(builder, value):
    ByteDataTrackAddValue(builder, value)

def ByteDataTrackEnd(builder):
    return builder.EndObject()

def End(builder):
    return ByteDataTrackEnd(builder)


class ByteDataTrackT(object):

    # ByteDataTrackT
    def __init__(self):
        self.value = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        byteDataTrack = ByteDataTrack()
        byteDataTrack.Init(buf, pos)
        return cls.InitFromObj(byteDataTrack)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, byteDataTrack):
        x = ByteDataTrackT()
        x._UnPack(byteDataTrack)
        return x

    # ByteDataTrackT
    def _UnPack(self, byteDataTrack):
        if byteDataTrack is None:
            return
        self.value = byteDataTrack.Value()

    # ByteDataTrackT
    def Pack(self, builder):
        ByteDataTrackStart(builder)
        ByteDataTrackAddValue(builder, self.value)
        byteDataTrack = ByteDataTrackEnd(builder)
        return byteDataTrack
