# automatically generated by the FlatBuffers compiler, do not modify
from GFLib.Anim.DynamicByteTrack import DynamicByteTrackT
from GFLib.Anim.FixedByteTrack import FixedByteTrackT
from GFLib.Anim.Framed16ByteTrack import Framed16ByteTrackT
from GFLib.Anim.Framed8ByteTrack import Framed8ByteTrackT


# namespace: Anim

class ByteTrack(object):
    NONE = 0
    FixedByteTrack = 1
    DynamicByteTrack = 2
    Framed16ByteTrack = 3
    Framed8ByteTrack = 4

def ByteTrackCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == ByteTrack().FixedByteTrack:
        return FixedByteTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ByteTrack().DynamicByteTrack:
        return DynamicByteTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ByteTrack().Framed16ByteTrack:
        return Framed16ByteTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ByteTrack().Framed8ByteTrack:
        return Framed8ByteTrackT.InitFromBuf(table.Bytes, table.Pos)
    return None
