# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Anim

import flatbuffers
from flatbuffers.compat import import_numpy

from GFLib.Anim.CommandTrack import CommandTrack, CommandTrackT

np = import_numpy()

class CommandAnimation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommandAnimation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommandAnimation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CommandAnimation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommandAnimation
    def Tracks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CommandTrack()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CommandAnimation
    def TracksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CommandAnimation
    def TracksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def CommandAnimationStart(builder):
    builder.StartObject(1)

def Start(builder):
    CommandAnimationStart(builder)

def CommandAnimationAddTracks(builder, tracks):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tracks), 0)

def AddTracks(builder, tracks):
    CommandAnimationAddTracks(builder, tracks)

def CommandAnimationStartTracksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTracksVector(builder, numElems):
    return CommandAnimationStartTracksVector(builder, numElems)

def CommandAnimationEnd(builder):
    return builder.EndObject()

def End(builder):
    return CommandAnimationEnd(builder)

try:
    from typing import List
except:
    pass

class CommandAnimationT(object):

    # CommandAnimationT
    def __init__(self):
        self.tracks = None  # type: List[CommandTrackT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        commandAnimation = CommandAnimation()
        commandAnimation.Init(buf, pos)
        return cls.InitFromObj(commandAnimation)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, commandAnimation):
        x = CommandAnimationT()
        x._UnPack(commandAnimation)
        return x

    # CommandAnimationT
    def _UnPack(self, commandAnimation):
        if commandAnimation is None:
            return
        if not commandAnimation.TracksIsNone():
            self.tracks = []
            for i in range(commandAnimation.TracksLength()):
                if commandAnimation.Tracks(i) is None:
                    self.tracks.append(None)
                else:
                    commandTrack_ = CommandTrackT.InitFromObj(commandAnimation.Tracks(i))
                    self.tracks.append(commandTrack_)

    # CommandAnimationT
    def Pack(self, builder):
        if self.tracks is not None:
            trackslist = []
            for i in range(len(self.tracks)):
                trackslist.append(self.tracks[i].Pack(builder))
            CommandAnimationStartTracksVector(builder, len(self.tracks))
            for i in reversed(range(len(self.tracks))):
                builder.PrependUOffsetTRelative(trackslist[i])
            tracks = builder.EndVector()
        CommandAnimationStart(builder)
        if self.tracks is not None:
            CommandAnimationAddTracks(builder, tracks)
        commandAnimation = CommandAnimationEnd(builder)
        return commandAnimation
