# automatically generated by the FlatBuffers compiler, do not modify
from GFLib.Anim.ByteDataTrack import ByteDataTrackT
from GFLib.Anim.FloatDataTrack import FloatDataTrackT
from GFLib.Anim.IntDataTrack import IntDataTrackT
from GFLib.Anim.StringDataTrack import StringDataTrackT


# namespace: Anim

class DataTrack(object):
    NONE = 0
    IntDataTrack = 1
    FloatDataTrack = 2
    ByteDataTrack = 3
    StringDataTrack = 4

def DataTrackCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == DataTrack().IntDataTrack:
        return IntDataTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == DataTrack().FloatDataTrack:
        return FloatDataTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == DataTrack().ByteDataTrack:
        return ByteDataTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == DataTrack().StringDataTrack:
        return StringDataTrackT.InitFromBuf(table.Bytes, table.Pos)
    return None
