# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Anim

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Framed8BooleanTrack(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Framed8BooleanTrack()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFramed8BooleanTrack(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Framed8BooleanTrack
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Framed8BooleanTrack
    def Frames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Framed8BooleanTrack
    def FramesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Framed8BooleanTrack
    def FramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Framed8BooleanTrack
    def FramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Framed8BooleanTrack
    def Bool(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Framed8BooleanTrack
    def BoolAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # Framed8BooleanTrack
    def BoolLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Framed8BooleanTrack
    def BoolIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Framed8BooleanTrackStart(builder):
    builder.StartObject(2)

def Start(builder):
    Framed8BooleanTrackStart(builder)

def Framed8BooleanTrackAddFrames(builder, frames):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(frames), 0)

def AddFrames(builder, frames):
    Framed8BooleanTrackAddFrames(builder, frames)

def Framed8BooleanTrackStartFramesVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartFramesVector(builder, numElems):
    return Framed8BooleanTrackStartFramesVector(builder, numElems)

def Framed8BooleanTrackAddBool(builder, bool):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bool), 0)

def AddBool(builder, bool):
    Framed8BooleanTrackAddBool(builder, bool)

def Framed8BooleanTrackStartBoolVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartBoolVector(builder, numElems):
    return Framed8BooleanTrackStartBoolVector(builder, numElems)

def Framed8BooleanTrackEnd(builder):
    return builder.EndObject()

def End(builder):
    return Framed8BooleanTrackEnd(builder)

try:
    from typing import List
except:
    pass

class Framed8BooleanTrackT(object):

    # Framed8BooleanTrackT
    def __init__(self):
        self.frames = None  # type: List[int]
        self.bool = None  # type: List[bool]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        framed8BooleanTrack = Framed8BooleanTrack()
        framed8BooleanTrack.Init(buf, pos)
        return cls.InitFromObj(framed8BooleanTrack)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, framed8BooleanTrack):
        x = Framed8BooleanTrackT()
        x._UnPack(framed8BooleanTrack)
        return x

    # Framed8BooleanTrackT
    def _UnPack(self, framed8BooleanTrack):
        if framed8BooleanTrack is None:
            return
        if not framed8BooleanTrack.FramesIsNone():
            if np is None:
                self.frames = []
                for i in range(framed8BooleanTrack.FramesLength()):
                    self.frames.append(framed8BooleanTrack.Frames(i))
            else:
                self.frames = framed8BooleanTrack.FramesAsNumpy()
        if not framed8BooleanTrack.BoolIsNone():
            if np is None:
                self.bool = []
                for i in range(framed8BooleanTrack.BoolLength()):
                    self.bool.append(framed8BooleanTrack.Bool(i))
            else:
                self.bool = framed8BooleanTrack.BoolAsNumpy()

    # Framed8BooleanTrackT
    def Pack(self, builder):
        if self.frames is not None:
            if np is not None and type(self.frames) is np.ndarray:
                frames = builder.CreateNumpyVector(self.frames)
            else:
                Framed8BooleanTrackStartFramesVector(builder, len(self.frames))
                for i in reversed(range(len(self.frames))):
                    builder.PrependUint8(self.frames[i])
                frames = builder.EndVector()
        if self.bool is not None:
            if np is not None and type(self.bool) is np.ndarray:
                bool = builder.CreateNumpyVector(self.bool)
            else:
                Framed8BooleanTrackStartBoolVector(builder, len(self.bool))
                for i in reversed(range(len(self.bool))):
                    builder.PrependBool(self.bool[i])
                bool = builder.EndVector()
        Framed8BooleanTrackStart(builder)
        if self.frames is not None:
            Framed8BooleanTrackAddFrames(builder, frames)
        if self.bool is not None:
            Framed8BooleanTrackAddBool(builder, bool)
        framed8BooleanTrack = Framed8BooleanTrackEnd(builder)
        return framed8BooleanTrack
