# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Anim

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Framed16FloatTrack(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Framed16FloatTrack()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFramed16FloatTrack(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Framed16FloatTrack
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Framed16FloatTrack
    def Frames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # Framed16FloatTrack
    def FramesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # Framed16FloatTrack
    def FramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Framed16FloatTrack
    def FramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Framed16FloatTrack
    def Float(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Framed16FloatTrack
    def FloatAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Framed16FloatTrack
    def FloatLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Framed16FloatTrack
    def FloatIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Framed16FloatTrackStart(builder):
    builder.StartObject(2)

def Start(builder):
    Framed16FloatTrackStart(builder)

def Framed16FloatTrackAddFrames(builder, frames):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(frames), 0)

def AddFrames(builder, frames):
    Framed16FloatTrackAddFrames(builder, frames)

def Framed16FloatTrackStartFramesVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartFramesVector(builder, numElems):
    return Framed16FloatTrackStartFramesVector(builder, numElems)

def Framed16FloatTrackAddFloat(builder, float):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(float), 0)

def AddFloat(builder, float):
    Framed16FloatTrackAddFloat(builder, float)

def Framed16FloatTrackStartFloatVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFloatVector(builder, numElems):
    return Framed16FloatTrackStartFloatVector(builder, numElems)

def Framed16FloatTrackEnd(builder):
    return builder.EndObject()

def End(builder):
    return Framed16FloatTrackEnd(builder)

try:
    from typing import List
except:
    pass

class Framed16FloatTrackT(object):

    # Framed16FloatTrackT
    def __init__(self):
        self.frames = None  # type: List[int]
        self.float = None  # type: List[float]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        framed16FloatTrack = Framed16FloatTrack()
        framed16FloatTrack.Init(buf, pos)
        return cls.InitFromObj(framed16FloatTrack)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, framed16FloatTrack):
        x = Framed16FloatTrackT()
        x._UnPack(framed16FloatTrack)
        return x

    # Framed16FloatTrackT
    def _UnPack(self, framed16FloatTrack):
        if framed16FloatTrack is None:
            return
        if not framed16FloatTrack.FramesIsNone():
            if np is None:
                self.frames = []
                for i in range(framed16FloatTrack.FramesLength()):
                    self.frames.append(framed16FloatTrack.Frames(i))
            else:
                self.frames = framed16FloatTrack.FramesAsNumpy()
        if not framed16FloatTrack.FloatIsNone():
            if np is None:
                self.float = []
                for i in range(framed16FloatTrack.FloatLength()):
                    self.float.append(framed16FloatTrack.Float(i))
            else:
                self.float = framed16FloatTrack.FloatAsNumpy()

    # Framed16FloatTrackT
    def Pack(self, builder):
        if self.frames is not None:
            if np is not None and type(self.frames) is np.ndarray:
                frames = builder.CreateNumpyVector(self.frames)
            else:
                Framed16FloatTrackStartFramesVector(builder, len(self.frames))
                for i in reversed(range(len(self.frames))):
                    builder.PrependUint16(self.frames[i])
                frames = builder.EndVector()
        if self.float is not None:
            if np is not None and type(self.float) is np.ndarray:
                float = builder.CreateNumpyVector(self.float)
            else:
                Framed16FloatTrackStartFloatVector(builder, len(self.float))
                for i in reversed(range(len(self.float))):
                    builder.PrependFloat32(self.float[i])
                float = builder.EndVector()
        Framed16FloatTrackStart(builder)
        if self.frames is not None:
            Framed16FloatTrackAddFrames(builder, frames)
        if self.float is not None:
            Framed16FloatTrackAddFloat(builder, float)
        framed16FloatTrack = Framed16FloatTrackEnd(builder)
        return framed16FloatTrack
