# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Anim

import flatbuffers
from flatbuffers.compat import import_numpy

from GFLib.Anim.SkinTrack import SkinTrackT, SkinTrack

np = import_numpy()

class SkinAnimation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SkinAnimation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSkinAnimation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SkinAnimation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SkinAnimation
    def Tracks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SkinTrack()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SkinAnimation
    def TracksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SkinAnimation
    def TracksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SkinAnimationStart(builder):
    builder.StartObject(1)

def Start(builder):
    SkinAnimationStart(builder)

def SkinAnimationAddTracks(builder, tracks):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tracks), 0)

def AddTracks(builder, tracks):
    SkinAnimationAddTracks(builder, tracks)

def SkinAnimationStartTracksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTracksVector(builder, numElems):
    return SkinAnimationStartTracksVector(builder, numElems)

def SkinAnimationEnd(builder):
    return builder.EndObject()

def End(builder):
    return SkinAnimationEnd(builder)

try:
    from typing import List
except:
    pass

class SkinAnimationT(object):

    # SkinAnimationT
    def __init__(self):
        self.tracks = None  # type: List[SkinTrackT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        skinAnimation = SkinAnimation()
        skinAnimation.Init(buf, pos)
        return cls.InitFromObj(skinAnimation)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, skinAnimation):
        x = SkinAnimationT()
        x._UnPack(skinAnimation)
        return x

    # SkinAnimationT
    def _UnPack(self, skinAnimation):
        if skinAnimation is None:
            return
        if not skinAnimation.TracksIsNone():
            self.tracks = []
            for i in range(skinAnimation.TracksLength()):
                if skinAnimation.Tracks(i) is None:
                    self.tracks.append(None)
                else:
                    skinTrack_ = SkinTrackT.InitFromObj(skinAnimation.Tracks(i))
                    self.tracks.append(skinTrack_)

    # SkinAnimationT
    def Pack(self, builder):
        if self.tracks is not None:
            trackslist = []
            for i in range(len(self.tracks)):
                trackslist.append(self.tracks[i].Pack(builder))
            SkinAnimationStartTracksVector(builder, len(self.tracks))
            for i in reversed(range(len(self.tracks))):
                builder.PrependUOffsetTRelative(trackslist[i])
            tracks = builder.EndVector()
        SkinAnimationStart(builder)
        if self.tracks is not None:
            SkinAnimationAddTracks(builder, tracks)
        skinAnimation = SkinAnimationEnd(builder)
        return skinAnimation
