# automatically generated by the FlatBuffers compiler, do not modify
from GFLib.Anim.DynamicVectorTrack import DynamicVectorTrackT
from GFLib.Anim.FixedVectorTrack import FixedVectorTrackT
from GFLib.Anim.Framed16VectorTrack import Framed16VectorTrackT
from GFLib.Anim.Framed8VectorTrack import Framed8VectorTrackT


# namespace: Anim

class VectorTrack(object):
    NONE = 0
    FixedVectorTrack = 1
    DynamicVectorTrack = 2
    Framed16VectorTrack = 3
    Framed8VectorTrack = 4

def VectorTrackCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == VectorTrack().FixedVectorTrack:
        return FixedVectorTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == VectorTrack().DynamicVectorTrack:
        return DynamicVectorTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == VectorTrack().Framed16VectorTrack:
        return Framed16VectorTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == VectorTrack().Framed8VectorTrack:
        return Framed8VectorTrackT.InitFromBuf(table.Bytes, table.Pos)
    return None
